[package]
name = "wasmcloud-nats"
version = "0.10.4"
authors = ["wasmCloud Team"]
edition = "2018"
homepage = "https://wasmcloud.dev"
repository = "https://github.com/wasmcloud/capability-providers"
description = "NATS capability provider for the wasmCloud host runtime"
license = "Apache-2.0"
documentation = "https://docs.rs/wasmcloud-nats"
readme = "README.md"
keywords = ["webassembly", "wasm", "wasi", "wasmcloud", "nats"]
categories = ["wasm", "api-bindings"]

[badges]
maintenance = { status = "actively-developed" }

[lib]
crate-type = ["cdylib", "rlib"]

[features]
# Enable if the provider will be statically compiled into a host
static_plugin = []

[dependencies]
wascap = "0.6.0"
wasmcloud-actor-messaging = "0.1.0"
wasmcloud-actor-core = "0.2.2"
log = "0.4.14"
env_logger = "0.8.2"
crossbeam-channel = "0.5.0"
crossbeam-utils = "^0.8.3"
nats = "0.9.6"
serde_bytes = "0.11.5"
rmp-serde = "0.15.4"
serde = {version = "1.0.123", features = ["derive"]}

[dependencies.wasmcloud-provider-core]
version = "0.1.0"
#path = "../../wasmcloud/crates/wasmcloud-provider-core"
