[package]
name = "wasmcloud-provider-nats"
version = "0.11.5"
edition = "2021"

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
chrono = "0.4"
crossbeam="0.8"
futures = "0.3"
log = "0.4"
nats = "0.13"
once_cell = "1.8"
rmp-serde = "0.15"
serde_bytes = "0.11"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
wascap = "0.6"
wasmbus-rpc = "0.6"
wasmcloud-interface-messaging = "0.3"

# test dependencies
[dev-dependencies]
wasmcloud-test-util = "0.2.1"

[[bin]]
name = "nats_messaging"
path = "src/main.rs"
