# codegen.toml
# Generates key value interface library

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces/keyvalue/keyvalue.smithy"

[[models]]
url = "https://cdn.jsdelivr.net/gh/wasmcloud/interfaces/core"
files = [ "wasmcloud-core.smithy", "wasmcloud-model.smithy" ]

[rust]
output_dir = ""

[[rust.files]]
path = "keyvalue.rs"
namespace = "org.wasmcloud.interface.keyvalue"



