# configuration for kv test

# name of compiled binary (usually project name unless overridden in [[bin]]
# Note that the path depends on whether cargo test is run with the `--release` flag
# Required
bin_path = "target/release/kv-vault"

# set RUST_LOG environment variable (default "info")
rust_log = "debug"

# set RUST_BACKTRACE (default: 0)
rust_backtrace = "1"

# nats should be running. Uncomment to override the default url
#nats_url = "127.0.0.1:4222"

# lattice prefix (default "default")
#lattice_rpc_prefix = "default"

# link name (default: "default")
#link_name = "default"

# name of contract under test
contract_id = "wasmcloud:keyvalue"
