name: NATS-KVCACHE-RELEASE

on:
  push:
    tags:
    - 'nats-kvcache-v*'

env:
  CARGO_TERM_COLOR: always
  working-directory: ./nats-kvcache
  REVISION: ${{ github.run_number }}

jobs:
  cargo_check:
    runs-on: ubuntu-latest
    services:
      nats:
        image: nats
        ports:
          - 6222:6222
          - 4222:4222
          - 8222:8222
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ env.working-directory }}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{ env.working-directory }}
    - name: Check fmt
      run: cargo fmt -- --check
      working-directory: ${{ env.working-directory }}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Run cargo clippy
        run: cargo clippy --all-features
        working-directory: ${{ env.working-directory }}

  github_release:
    needs: [cargo_check, clippy_check]
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

  crates_release:
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cargo login
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
        run: cargo login ${{ env.CRATES_TOKEN }}
      - name: Cargo publish
        run: cargo publish --no-verify
        working-directory: ${{ env.working-directory }}
