name: NATS-RELEASE

on:
  push:
    tags:
    - 'nats-v*'

env:
  CARGO_TERM_COLOR: always
  working-directory: ./nats
  WASH_ISSUER_KEY: ${{ secrets.WASMCLOUD_ACCOUNT_OFFICIAL }}
  WASH_SUBJECT_KEY: ${{ secrets.WASMCLOUD_NATS }}
  WASH_REG_USER:  ${{ secrets.AZURECR_PUSH_USER }}
  WASH_REG_PASSWORD:  ${{ secrets.AZURECR_PUSH_PASSWORD }}
  REVISION: ${{ github.run_number }}

jobs:
  cargo_check:
    services:
      nats:
        image: nats
        ports:
          - 6222:6222
          - 4222:4222
          - 8222:8222
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ env.working-directory }}
    - name: Start nats container
      run: docker run --rm -d -p 4222:4222 nats:2.3 
    - name: Run tests
      run: make test
      working-directory: ${{ env.working-directory }}
    - name: Check fmt
      run: cargo fmt -- --check
      working-directory: ${{ env.working-directory }}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Run cargo clippy
        run: cargo clippy --all-features
        working-directory: ${{ env.working-directory }}

  github_release:
    needs: [cargo_check, clippy_check]
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

  crates_release:
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cargo login
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
        run: cargo login ${{ env.CRATES_TOKEN }}
      - name: Cargo publish
        run: cargo publish --no-verify
        working-directory: ${{ env.working-directory }}

  artifact_release:
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -s https://packagecloud.io/install/repositories/wasmCloud/core/script.deb.sh | sudo bash
          sudo apt install wash
      - run: cargo install --git https://github.com/ChrisRx/cross --branch add-darwin-target --force # Installing from feature branch until PR merged
      - name: build-par
        run: make par
        working-directory: ${{ env.working-directory }}
      # Push artifact to https://AZURECR/nats:VERSION
      - name: push-par
        run: |
          VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].version')
          NAME=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].name')
          TAGNAME=$(echo $NAME | sed 's/wasmcloud-//')
          URL=${{secrets.AZURECR_PUSH_URL}}/$TAGNAME:$VERSION
          wash reg push $URL $NAME.par.gz
        working-directory: ${{ env.working-directory }}
