name: REDISSTREAMS

on:
  push:
    branches: [ main ]
    paths:
    - "redis-streams/**"
  pull_request:
    branches: [ main ]
    paths:
    - "redis-streams/**"

env:
  CARGO_TERM_COLOR: always
  working-directory: ./redis-streams

jobs:
  cargo_check:
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{env.working-directory}}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{env.working-directory}}
    - name: Check fmt
      run: cargo fmt -- --check
      working-directory: ${{env.working-directory}}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Run cargo clippy
        run: cargo clippy --all-features
        working-directory: ${{env.working-directory}}
