# configuration for httpclient test

# name of compiled binary (usually project name unless overridden in [[bin]]
# Required
bin_path = "target/debug/httpclient"

# set RUST_LOG environment variable (default "info")
rust_log = "debug"

# set RUST_BACKTRACE (default: 0)
rust_backtrace = "1"

# nats should be running. Uncomment to override the default url
#nats_url = "0.0.0.0:4222"

# redis should be running. Uncomment to override the default url
#redis_url = "0.0.0.0:6379"

# lattice prefix (default "default")
#lattice_rpc_prefix = "default"

# link name (default: "default")
#link_name = "default"

# name of contract under test
contract_id = "wasmcloud:httpclient"

# optional delay to wait for provider to start
#start_delay_sec = 2