[target.armv7-unknown-linux-gnueabihf]
image = "wasmcloud/cross:armv7-unknown-linux-gnueabihf"

[target.aarch64-unknown-linux-gnu]
image = "wasmcloud/cross:aarch64-unknown-linux-gnu"

[target.mips-unknown-linux-gnu]
image = "wasmcloud/cross:mips-unknown-linux-gnu"

[target.mipsel-unknown-linux-gnu]
image = "wasmcloud/cross:mipsel-unknown-linux-gnu"

[target.mips64-unknown-linux-gnuabi64]
image = "wasmcloud/cross:mips64-unknown-linux-gnuabi64"

[target.mips64el-unknown-linux-gnuabi64]
image = "wasmcloud/cross:mips64el-unknown-linux-gnuabi64"

[target.x86_64-apple-darwin]
image = "wasmcloud/cross:x86_64-apple-darwin"

[target.aarch64-apple-darwin]
image = "wasmcloud/cross:aarch64-apple-darwin"

[target.x86_64-unknown-linux-gnu]
image = "wasmcloud/cross:x86_64-unknown-linux-gnu"
