[package]
name = "wasccgraph-actor"
version = "0.0.3"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"
homepage = "https://wascc.dev"
repository = "https://github.com/wascc/redisgraph"
description = "waSCC Actor Support for graph database capability providers"
license = "Apache-2.0"
documentation = "https://docs.rs/wasccgraph-actor"
readme = "README.md"
keywords = ["webassembly", "wasm", "graphdb", "graph", "wascc"]
categories = ["wasm", "api-bindings", "database"]


[dependencies]
wasccgraph-common = "0.0.2"
wascc-actor = "0.7.2"
