[package]
name = "graph-actor"
version = "0.1.0"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = "0.4.0"
wasmcloud-actor-graphdb = { version = "0.1.1", features = ["guest"] }
wasmcloud-actor-http-server = { version = "0.1.0", features = ["guest"]}
wasmcloud-actor-core = { version = "0.2.0", features = ["guest"]}
serde_json = "1.0.53"
log = "0.4.8"

[profile.release]
# Optimize for small code size
opt-level = "s"
