[package]
name = "graph-actor"
version = "0.0.1"
authors = ["Kevin Hoffman <alothien@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wapc-guest = "0.4.0"
actor-graphdb = { path = "../../../../actor-interfaces/rust/graphdb", features = ["guest"] }
actor-http-server = { git = "https://github.com/wasmCloud/actor-interfaces", branch = "main" }
#actor-graphdb = { git = "https://github.com/wasmCloud/actor-interfaces", branch = "graphdb", features = ["guest"]}
actor-core = { git = "https://github.com/wasmCloud/actor-interfaces", branch = "main", features = ["guest"]}
serde_json = "1.0.53"
log = "0.4.8"

[profile.release]
# Optimize for small code size
opt-level = "s"
