[package]
name = "wasmcloud-provider-httpserver"
version = "0.14.8"
edition = "2021"

[dependencies]
async-trait = "0.1"
base64 = "0.13"
bytes = "1.0"
chrono = "0.4"
crossbeam="0.8"
futures = "0.3"
http = "0.2"
log = "0.4"
once_cell = "1.8"
rmp-serde = "0.15"
serde_bytes = "0.11"
serde_json = "1.0"
serde = {version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
warp = {version="0.3", features=["tls"]}
wasmcloud-interface-httpserver = "0.3"
wasmbus-rpc = "0.6"

[dev-dependencies]
assert_matches = "1.5"
blake2 = "0.9"
reqwest = { version = "0.11", features = ["json"]}
wasmcloud-test-util = "0.1.9"

[lib]
name = "wasmcloud_provider_httpserver"
path = "src/lib.rs"

[[bin]]
name = "httpserver"
path = "bin/main.rs"

