name: HTTPSERVER-RELEASE

on:
  push:
    tags:
    - 'httpserver-v*'

env:
  CARGO_TERM_COLOR: always
  working-directory: ./httpserver
  DESTINATION: httpserver.par.gz #aka the filename of the parJEEzy
  WASH_ISSUER_KEY: ${{ secrets.WASMCLOUD_ACCOUNT_OFFICIAL }}
  WASH_SUBJECT_KEY: ${{ secrets.WASMCLOUD_HTTPSERVER }}
  WASH_REG_USER:  ${{ secrets.AZURECR_PUSH_USER }}
  WASH_REG_PASSWORD:  ${{ secrets.AZURECR_PUSH_PASSWORD }}
  REVISION: ${{ github.run_number }}

jobs:
  cargo_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ env.working-directory }}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{ env.working-directory }}
    - name: Check fmt
      run: cargo fmt -- --check
      working-directory: ${{ env.working-directory }}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Run cargo clippy
        run: cargo clippy --all-features
        working-directory: ${{ env.working-directory }}

  github_release:
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: true

  crates_release:
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Cargo login
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_PUBLISH_TOKEN }}
        run: cargo login ${{ env.CRATES_TOKEN }}
      - name: Cargo publish
        run: cargo publish --no-verify

  artifact_release:
    needs: github_release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          curl -s https://packagecloud.io/install/repositories/wasmCloud/core/script.deb.sh | sudo bash
          sudo apt install wash
      - run: cargo install --git https://github.com/ChrisRx/cross --branch add-darwin-target --force # Installing from feature branch until PR merged
      - name: build-par
        run: make par
        working-directory: ${{ env.working-directory }}
      # Push artifact to https://AZURECR/httpserver:VERSION
      - name: push-par
        run: |
          VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[].version')
          URL=${{secrets.AZURECR_PUSH_URL}}/httpserver:$VERSION
          wash reg push $URL ${{ env.DESTINATION }}
        working-directory: ${{ env.working-directory }}
