name: NATS

on:
  push:
    tags:
    - 'nats-v*'

env:
  CARGO_TERM_COLOR: always
  working-directory: ./nats
  DESTINATION: nats.par.gz
  WASH_ISSUER_KEY: ${{ secrets.WASMCLOUD_ACCOUNT_OFFICIAL }}
  WASH_SUBJECT_KEY: ${{ secrets.WASMCLOUD_NATS }}
  WASH_REG_USER:  ${{ secrets.AZURECR_PUSH_USER }}
  WASH_REG_PASSWORD:  ${{ secrets.AZURECR_PUSH_PASSWORD }}
  REVISION: ${{ env.GITHUB_RUN_NUMBER }}

jobs:
  cargo_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
      working-directory: ${{ env.working-directory }}
    - name: Run tests
      run: cargo test --verbose
      working-directory: ${{ env.working-directory }}
    - name: Check fmt
      run: cargo fmt -- --check
      working-directory: ${{ env.working-directory }}

  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add clippy
      - name: Run cargo clippy
        run: cargo clippy --all-features
        working-directory: ${{ env.working-directory }}

  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo install --git https://github.com/wasmcloud/wash --branch main --tag v0.1.13 --force
      - run: cargo install cross --version 0.2.1 --force
      - name: build-par
        run: make par
        working-directory: ${{ env.working-directory }}
      - name: push-par
        run: wash reg push ${{ secrets.AZURECR_PUSH_URL }} ${{ env.DESTINATION }}
        working-directory: ${{ env.working-directory }}
      
